### PR TITLE
Improved code style and legibility and added limit option

### PR DESCRIPTION
**Pull request by eusonlito**
I hope that can be interesting for you.
- Some code improvements (nested ifs and preload regular expressions).
- Improved styles removing some strong colors.
- Added limit option.

### CODE REVIEW

**Comment by jakerella** [comment]
Thanks! I'm at a conference, but I'll try to review soon.

**Comment by eusonlito** [comment]
Hi! remember me :)

**Comment by jakerella** [comment]
SO SORRY!
Totally my bad here. I've bookmarked this and will get to it in 2 weeks... you won't believe it, but I'm about to head out on vacation again. My first one since back then. ;)

**Comment by eusonlito** [comment]
No problem!! I'm not your boss ;)

**Comment by jakerella** [comment]
Hello again... I want to thank you for working so hard on this code. I really hope that it has served you well. That said, you've submitted an enormous amount of changes for such a small library. In addition to the `limit` option there are numerous changes that aren't just "style" or "legibility" but large reorganizations of the code. I'm not opposed to large refactoring, but it's difficult for me to process such a large change, especially without unit tests (which is 100% my fault).

At this point, I don't think I can just merge this PR in, there's just too much that I can't verify easily. Of course, you can always keep your fork active, and I would be happy to merge in the `limit` functionality by itself if you wanted to submit that on its own. Additionally, if we were to create unit tests I'd be much more comfortable looking at these changes.

Essentially this just comes down to there being way too much for a single PR. Hope this doesn't deter you from helping this or other projects!!

**Comment by eusonlito** [comment]
Ok, no problem! Anyway thanks for chek my code. Regards!

**Pull request closed without merging**
